export type VocabItem = {
  term: string;
  pos: string;
  meaning: string;
  family?: string[];
};

export type PhraseItem = { term: string; meaning: string };
export type SentenceItem = { en: string; zh: string };

export type Unit = {
  id: number;
  title: string;
  color: string;
  vocab: VocabItem[];
  phrases: PhraseItem[];
  sentences: SentenceItem[];
};

export const units: Unit[] = [
  {
    id: 1,
    title: "Look it up!",
    color: "#7057c7",
    vocab: [
      { term: "dinosaur", pos: "n.", meaning: "恐龙" },
      { term: "intelligent", pos: "adj.", meaning: "有才智的；聪明的", family: ["intelligence n. 才智；智慧"] },
      { term: "talented", pos: "adj.", meaning: "有才能的；天才的", family: ["talent n. 天才；天资；天赋"] },
      { term: "artistic", pos: "adj.", meaning: "有艺术天赋的；（尤指）有美术才能的", family: ["artist n. 艺术家；（尤指）画家", "art n. 艺术；美术"] },
      { term: "perhaps", pos: "adv.", meaning: "可能；大概；也许" },
      { term: "notebook", pos: "n.", meaning: "笔记本" },
      { term: "vehicle", pos: "n.", meaning: "交通工具；车辆" },
      { term: "prehistoric", pos: "adj.", meaning: "史前的", family: ["prehistory n. 史前时期", "history n. 历史", "historic adj. 历史上著名（或重要）的；可名垂青史的", "historical adj.（有关）历史的"] },
      { term: "completely", pos: "adv.", meaning: "完全地；彻底地", family: ["complete adj. 完全的；彻底的"] },
      { term: "original", pos: "adj.", meaning: "原来的；起初的", family: ["originally adv. 原来；起初", "origin n. 起源；源头；起因"] },
      { term: "birth", pos: "n.", meaning: "出生" },
      { term: "suffering", pos: "n.", meaning: "苦难；疼痛", family: ["suffer v.（因疾病、痛苦、悲伤等）受苦；受难；受折磨"] },
      { term: "artist", pos: "n.", meaning: "艺术家；（尤指）画家" },
      { term: "piece", pos: "n.", meaning: "（音乐作品的）一首" },
      { term: "death", pos: "n.", meaning: "死；死亡" },
      { term: "whole", pos: "adj.", meaning: "全部的；所有的" },
      { term: "editor", pos: "n.", meaning: "（书籍的）编辑" },
      { term: "organize", pos: "v.", meaning: "安排；组织", family: ["organization n. 安排；组织", "organized adj. 有组织的；系统的"] },
      { term: "order", pos: "n.", meaning: "顺序" },
      { term: "record", pos: "v.", meaning: "记录" },
    ],
    phrases: [
      { term: "die out", meaning: "灭绝" },
      { term: "a type of", meaning: "一种" },
      { term: "be related to", meaning: "与……属于同一种类" },
      { term: "general education", meaning: "通识教育" },
      { term: "go back a long way", meaning: "历史悠久" },
      { term: "be similar to", meaning: "与……相似" },
      { term: "alphabetical order", meaning: "字母顺序" },
      { term: "play an important role", meaning: "起到重要作用" },
    ],
    sentences: [
      { en: "He was a true genius, and his paintings and inventions changed the way we think about art and science.", zh: "他是一个真正的天才人物，他的绘画和发明改变了我们对艺术和科学的看法。" },
      { en: "Some were as small as chickens, and others were as big as ten elephants.", zh: "有些（恐龙）和鸡一样小，其他的有十头大象那么大。" },
      { en: "Some scientists think the world became too cold for dinosaurs.", zh: "一些科学家认为世界对恐龙来说太冷了。" },
      { en: "Some believe there was not enough food for dinosaurs.", zh: "一些（科学家）认为恐龙没有足够的食物。" },
      { en: "It’s always useful to have an encyclopaedia around the house.", zh: "在家里有一本百科全书总是有用的。" },
    ],
  },
  {
    id: 2,
    title: "Amazing numbers",
    color: "#1aa6b7",
    vocab: [
      { term: "flight", pos: "n.", meaning: "（尤指乘飞机的）航程" },
      { term: "schedule", pos: "n.", meaning: "日程安排" },
      { term: "everywhere", pos: "adv.", meaning: "到处；各个地方" },
      { term: "challenge", pos: "v.", meaning: "向（某人）挑战" },
      { term: "prize", pos: "n.", meaning: "奖赏；奖励" },
      { term: "promise", pos: "v.", meaning: "承诺；保证" },
      { term: "chessboard", pos: "n.", meaning: "国际象棋棋盘" },
      { term: "silver", pos: "n.", meaning: "银" },
      { term: "reply", pos: "v.", meaning: "回复；答复" },
      { term: "hesitation", pos: "n.", meaning: "犹豫", family: ["hesitate v.（对某事）犹豫；迟疑不决"] },
      { term: "wonder", pos: "v.", meaning: "想知道；琢磨" },
      { term: "agree", pos: "v.", meaning: "同意；赞成", family: ["agreement n.（意见或看法）一致", "disagree v. 不同意；持不同意见；有分歧", "disagreement n. 意见不一；分歧；争论"] },
      { term: "per cent", pos: "n.", meaning: "百分之……" },
      { term: "currently", pos: "adv.", meaning: "目前；当前", family: ["current adj. 现时发生的；当前的；现在的"] },
      { term: "check", pos: "v.", meaning: "检查；核查" },
      { term: "budget", pos: "n.", meaning: "预算" },
      { term: "province", pos: "n.", meaning: "省份" },
      { term: "sharply", pos: "adv.", meaning: "急剧地；突然大幅度地", family: ["sharp adj.（变化）急剧的；骤然的；锋利的"] },
      { term: "count", pos: "v.", meaning: "计算（或清点）总数" },
      { term: "system", pos: "n.", meaning: "系统" },
      { term: "symbol", pos: "n.", meaning: "符号；记号" },
      { term: "represent", pos: "v.", meaning: "代表" },
      { term: "exactly", pos: "adv.", meaning: "准确地；确切地", family: ["exact adj. 精确的；准确的"] },
    ],
    phrases: [
      { term: "flight schedule", meaning: "航班时刻表" },
      { term: "price tag", meaning: "价格标签" },
      { term: "for a moment", meaning: "片刻；一会儿" },
      { term: "without hesitation", meaning: "毫不犹豫" },
      { term: "go up", meaning: "上升" },
      { term: "go down", meaning: "下降" },
      { term: "write down", meaning: "写下；记下" },
      { term: "instead of", meaning: "代替；作为……的替换" },
    ],
    sentences: [
      { en: "‘You can have any prize if you win the game,’ the king promised the old man.", zh: "国王答应老人：“如果你赢了比赛，你可以得到任何奖品。”" },
      { en: "After thinking about it for a moment, the king agreed.", zh: "想了一会儿之后，国王同意了。" },
      { en: "He looked at the small piece of gold in his hand and wondered what to do with it.", zh: "他看着手里的一小块金子，琢磨着该拿它怎么办。" },
      { en: "Instead of using tally sticks, people began using different abstract symbols to represent different numbers.", zh: "代替使用计数棍，人们开始使用不同的抽象符号来代表不同的数字。" },
    ],
  },
  {
    id: 3,
    title: "Our digital lives",
    color: "#3d8fd1",
    vocab: [
      { term: "network", pos: "n.", meaning: "网络" },
      { term: "flood", pos: "n.", meaning: "洪水；水灾" },
      { term: "multimedia", pos: "n.", meaning: "多媒体" },
      { term: "expert", pos: "n.", meaning: "专家" },
      { term: "mobile", pos: "adj.", meaning: "可移动的" },
      { term: "payment", pos: "n.", meaning: "付款；支付", family: ["pay v. 付费"] },
      { term: "warn", pos: "v.", meaning: "提醒注意；警告" },
      { term: "treatment", pos: "n.", meaning: "治疗；疗法", family: ["treat v. 医疗；医治；治疗"] },
      { term: "data", pos: "n.", meaning: "数据" },
      { term: "company", pos: "n.", meaning: "公司" },
      { term: "traffic", pos: "n.", meaning: "路上行驶的车辆；交通" },
      { term: "flow", pos: "v.", meaning: "（人或事物）涌流；流动" },
      { term: "smoothly", pos: "adv.", meaning: "平稳地；连续而流畅地", family: ["smooth adj. 平整的；平坦的；平滑的；光滑的；平稳的；连续而流畅的"] },
      { term: "laptop", pos: "n.", meaning: "笔记本电脑" },
      { term: "screen", pos: "n.", meaning: "屏幕" },
      { term: "weight", pos: "n.", meaning: "重量", family: ["weigh v. 有……重；称重量"] },
      { term: "digital", pos: "adj.", meaning: "数码的" },
      { term: "social", pos: "adj.", meaning: "社交的", family: ["society n. 社会"] },
      { term: "message", pos: "n.", meaning: "（书面或口头的）信息" },
      { term: "interview", pos: "v.", meaning: "采访", family: ["interviewee n. 接受采访者", "interviewer n. 采访者"] },
      { term: "positive", pos: "adj.", meaning: "正面的；积极的" },
      { term: "negative", pos: "adj.", meaning: "消极的" },
      { term: "effect", pos: "n.", meaning: "影响" },
      { term: "opinion", pos: "n.", meaning: "意见；看法" },
      { term: "novel", pos: "n.", meaning: "（长篇）小说" },
      { term: "comment", pos: "n.", meaning: "评论" },
      { term: "basis", pos: "n.", meaning: "基础", family: ["basic adj. 基础的；基本的", "base n. 基础 v. 以……为据点（或大本营等）"] },
      { term: "microprocessor", pos: "n.", meaning: "微处理器" },
      { term: "microchip", pos: "n.", meaning: "微芯片；芯片" },
      { term: "major", pos: "adj.", meaning: "主要的；重要的" },
      { term: "breakthrough", pos: "n.", meaning: "突破；重大进展" },
      { term: "electronic", pos: "adj.", meaning: "电子的" },
      { term: "software", pos: "n.", meaning: "软件" },
      { term: "app", pos: "n.", meaning: "（application 的缩写）应用程序；应用软件" },
      { term: "era", pos: "n.", meaning: "时代；纪元" },
      { term: "download", pos: "v.", meaning: "下载" },
      { term: "tiny", pos: "adj.", meaning: "微小的" },
    ],
    phrases: [
      { term: "connect to", meaning: "连接" },
      { term: "bring big changes to", meaning: "给……带来重大变化" },
      { term: "mobile payment", meaning: "移动支付" },
      { term: "take…for example", meaning: "以……为例" },
      { term: "rubbish bin", meaning: "垃圾箱" },
      { term: "social media", meaning: "社交媒体" },
      { term: "in person", meaning: "亲自；亲身" },
      { term: "stay in touch with…", meaning: "与……保持联系" },
      { term: "the general public", meaning: "公众；大众" },
      { term: "look up", meaning: "（在词典、参考书中或通过电脑）查阅" },
    ],
    sentences: [
      { en: "There will be fewer accidents because cars will drive themselves, and they will share data with the smart city network.", zh: "事故将更少，因为汽车将自动驾驶，并且它们将与智能城市网络共享数据。" },
      { en: "Some computers are even smarter than human beings.", zh: "有些电脑甚至比人类聪明。" },
      { en: "I think human beings are the smartest.", zh: "我认为人类是最聪明的。" },
      { en: "This makes our online messages more interesting to read.", zh: "这使得我们的在线消息读起来更有趣。" },
    ],
  },
  {
    id: 4,
    title: "Inventions",
    color: "#e18a26",
    vocab: [
      { term: "balloon", pos: "n.", meaning: "气球" },
      { term: "wheel", pos: "n.", meaning: "轮；车轮" },
      { term: "central", pos: "adj.", meaning: "在中心的", family: ["center n. 中心"] },
      { term: "although", pos: "conj.", meaning: "虽然；尽管；即使" },
      { term: "attach", pos: "v.", meaning: "把……固定；把……附（在……上）" },
      { term: "pull", pos: "v.", meaning: "拉；拽；扯；拖" },
      { term: "international", pos: "adj.", meaning: "国际的" },
      { term: "path", pos: "n.", meaning: "小路；小径" },
      { term: "technique", pos: "n.", meaning: "技巧；技艺", family: ["technical adj. 技巧的；技艺的", "technically adv. 在专业上；在技巧上；在技艺上"] },
      { term: "depend", pos: "v.", meaning: "需要；依靠" },
      { term: "doubt", pos: "n.", meaning: "疑惑；疑问" },
      { term: "personally", pos: "adv.", meaning: "就个人意见", family: ["personal adj. 个人的；私人的", "personality n. 性格；个性；人格"] },
      { term: "prediction", pos: "n.", meaning: "预言；预测", family: ["predict v. 预言；预料；预测"] },
      { term: "statement", pos: "n.", meaning: "说明" },
      { term: "benefit", pos: "n.", meaning: "益处；优势", family: ["beneficial adj. 有利的；有裨益的；有用的"] },
      { term: "wing", pos: "n.", meaning: "（飞行器的）翅膀；机翼" },
      { term: "distance", pos: "n.", meaning: "距离" },
      { term: "petrol", pos: "n.", meaning: "汽油" },
      { term: "avoid", pos: "v.", meaning: "避免；防止" },
      { term: "anywhere", pos: "adv.", meaning: "在（或去）任何地方" },
      { term: "notice", pos: "v.", meaning: "看（或听）到；注意到" },
      { term: "type", pos: "n.", meaning: "（印刷用的）活字" },
      { term: "mixture", pos: "n.", meaning: "混合物" },
      { term: "heat", pos: "v.", meaning: "加热；变热" },
      { term: "press", pos: "v.", meaning: "（被）压" },
      { term: "metal", pos: "n.", meaning: "金属" },
    ],
    phrases: [
      { term: "steam locomotive", meaning: "蒸汽机车" },
      { term: "crewed spacecraft", meaning: "载人航天器" },
      { term: "on foot", meaning: "步行" },
      { term: "a number of", meaning: "几个；若干" },
      { term: "take place", meaning: "发生；进行" },
      { term: "for instance", meaning: "例如；比如" },
      { term: "large amounts of", meaning: "大量" },
      { term: "international trade", meaning: "国际贸易" },
      { term: "depend on", meaning: "依靠；依赖" },
      { term: "3D printer", meaning: "3D 打印机" },
      { term: "without doubt", meaning: "毫无疑问" },
      { term: "of all time", meaning: "自古以来；有史以来" },
      { term: "make fun of", meaning: "取笑；拿……开玩笑" },
      { term: "traffic jam", meaning: "堵车；交通阻塞" },
    ],
    sentences: [
      { en: "Although this meant that people could travel further and faster, transporting large amounts of goods was still a difficult job.", zh: "尽管这意味着人们可以走得更远、更快，但运输大量货物仍然是一项困难的工作。" },
      { en: "The wheel not only changed the way humans move, but it also allowed us to build all types of amazing machines.", zh: "轮子不仅改变了人类的移动方式，还使我们能够制造出各种类型的神奇机器。" },
      { en: "A candle does not produce as much light as a light bulb.", zh: "蜡烛产生的光不如灯泡产生的多。" },
    ],
  },
  {
    id: 5,
    title: "Going on an exchange trip",
    color: "#e56b67",
    vocab: [
      { term: "exchange", pos: "n.", meaning: "交流" },
      { term: "nervous", pos: "adj.", meaning: "焦虑的；担忧的" },
      { term: "grateful", pos: "adj.", meaning: "感激的" },
      { term: "chopstick", pos: "n.", meaning: "筷子" },
      { term: "tour", pos: "n.", meaning: "旅行；旅游", family: ["tourist n. 游客", "tourism n. 旅游业"] },
      { term: "tai chi", pos: "n.", meaning: "太极（拳）" },
      { term: "yet", pos: "adv.", meaning: "尚（未）；还；仍" },
      { term: "independent", pos: "adj.", meaning: "自主的", family: ["dependent adj. 依赖的"] },
      { term: "content", pos: "n.", meaning: "内容" },
      { term: "feeling", pos: "n.", meaning: "感觉；感情" },
      { term: "shock", pos: "n.", meaning: "震惊；令人震惊的事", family: ["shocked adj. 震惊的", "shocking adj. 令人震惊的"] },
      { term: "foreign", pos: "adj.", meaning: "外国的", family: ["foreigner n. 外国人"] },
      { term: "confused", pos: "adj.", meaning: "糊涂的；迷惑的", family: ["confusing adj. 令人困惑的", "confuse v. 使迷惑"] },
      { term: "anxious", pos: "adj.", meaning: "焦虑的；忧虑的", family: ["anxiety n. 焦虑；忧虑"] },
      { term: "phase", pos: "n.", meaning: "阶段；时期" },
      { term: "honeymoon", pos: "n.", meaning: "蜜月" },
      { term: "unfamiliar", pos: "adj.", meaning: "陌生的；不熟悉的", family: ["familiar adj. 熟悉的"] },
      { term: "homesick", pos: "adj.", meaning: "想家的" },
      { term: "lonely", pos: "adj.", meaning: "孤独的" },
      { term: "deal", pos: "v.", meaning: "对付；应付" },
      { term: "expect", pos: "v.", meaning: "期待；盼望", family: ["expectation n. 期待；盼望"] },
      { term: "situation", pos: "n.", meaning: "情况" },
      { term: "accept", pos: "v.", meaning: "接受" },
      { term: "adaptation", pos: "n.", meaning: "适应", family: ["adapt v. 使适应"] },
    ],
    phrases: [
      { term: "Beijing opera", meaning: "京剧" },
      { term: "turn…into…", meaning: "使……变成……" },
      { term: "host family", meaning: "寄宿家庭" },
      { term: "snake its way", meaning: "蜿蜒" },
      { term: "no doubt", meaning: "无疑；很可能" },
      { term: "as well", meaning: "也；还" },
      { term: "come over", meaning: "短暂造访" },
      { term: "culture shock", meaning: "文化冲击" },
      { term: "deal with", meaning: "解决；处理" },
      { term: "feel at home", meaning: "感到舒适自在" },
    ],
    sentences: [
      { en: "I’m really grateful that they let me stay in their home.", zh: "他们让我住在他们家，我真的很感激。" },
      { en: "‘I’ve watched videos about the Great Wall before, but seeing it in person is definitely an unforgettable experience!’ says Lisa.", zh: "莉萨说：“我以前看过关于长城的视频，但亲眼看到它绝对是一次难忘的经历。”" },
      { en: "I plan to keep in touch with them when I return home.", zh: "我打算回家后和他们保持联系。" },
      { en: "For example, she has not seen the Great Wall yet, and she has not been to the Summer Palace either.", zh: "例如，她还没见过长城，她也没去过颐和园。" },
      { en: "If you travel to a foreign country, you may feel confused, strange or anxious.", zh: "如果你去国外旅行，你可能会感到困惑、陌生或焦虑。" },
      { en: "You start to accept the local culture, and you also learn how to deal with the things you do not like.", zh: "你开始接受当地的文化，你也学会了如何处理你不喜欢的事情。" },
    ],
  },
  {
    id: 6,
    title: "Wisdom counts",
    color: "#4aaf75",
    vocab: [
      { term: "author", pos: "n.", meaning: "作者；作家", family: ["authorship n. 作者身份"] },
      { term: "remains", pos: "n.", meaning: "遗迹；遗址" },
      { term: "locate", pos: "v.", meaning: "把……安置在（或建造于）", family: ["located adj. 位于", "location n. 位置"] },
      { term: "soldier", pos: "n.", meaning: "士兵" },
      { term: "captain", pos: "n.", meaning: "首领；领导者" },
      { term: "empty", pos: "adj.", meaning: "空的" },
      { term: "victory", pos: "n.", meaning: "胜利；成功" },
      { term: "joke", pos: "n.", meaning: "笑话；玩笑" },
      { term: "midnight", pos: "n.", meaning: "午夜" },
      { term: "except", pos: "prep.", meaning: "除……之外", family: ["exception n. 例外"] },
      { term: "hide", pos: "v.", meaning: "藏；隐藏" },
      { term: "secretly", pos: "adv.", meaning: "秘密地", family: ["secret adj. 秘密的 n. 秘密"] },
      { term: "enter", pos: "v.", meaning: "进来；进入" },
      { term: "succeed", pos: "v.", meaning: "达到目的；成功", family: ["success n. 成功"] },
      { term: "trick", pos: "n.", meaning: "诡计", family: ["tricky adj. 诡计多端的"] },
      { term: "fight", pos: "v.", meaning: "打仗；战斗", family: ["fighter n. 战士"] },
      { term: "beat", pos: "v.", meaning: "打败（某人）；敲打" },
      { term: "pretend", pos: "v.", meaning: "假装；佯装" },
      { term: "enemy", pos: "n.", meaning: "敌人" },
      { term: "fail", pos: "v.", meaning: "失败；未能（做到）", family: ["failed adj. 失败的", "failure n. 失败"] },
      { term: "therefore", pos: "adv.", meaning: "因此；所以" },
      { term: "within", pos: "prep.", meaning: "在（某段时间）之内" },
      { term: "fill", pos: "v.", meaning: "（使）充满；（使）装满" },
      { term: "towards", pos: "prep.", meaning: "向；朝；对着" },
      { term: "attack", pos: "n.", meaning: "袭击；攻击" },
      { term: "fog", pos: "n.", meaning: "雾" },
    ],
    phrases: [
      { term: "make jokes about", meaning: "开……的玩笑" },
      { term: "except for", meaning: "除……之外" },
      { term: "make one’s way to…", meaning: "前往……" },
      { term: "take over", meaning: "接管；夺取控制" },
      { term: "succeed in", meaning: "在……方面成功" },
      { term: "be tired of", meaning: "厌烦" },
      { term: "go on board", meaning: "上船" },
      { term: "be jealous of", meaning: "嫉妒" },
      { term: "be full of", meaning: "装满；充满" },
    ],
    sentences: [
      { en: "Outside the main gate of the city stood a huge wooden horse.", zh: "一匹巨大的木马矗立在城外。" },
      { en: "Then they made sure all the gates of the city were locked, and went to bed.", zh: "随后他们确认城门已全部锁好，便去睡了。" },
      { en: "By midnight, the main square was empty, except for the huge horse.", zh: "到了午夜，主广场空荡荡的，除了那匹巨大的木马。" },
      { en: "In the end, they succeeded in capturing it in just one night with a clever trick—and without any fighting.", zh: "最终，他们巧施妙计，在短短一个晚上便成功将其攻取——而且没有发生任何战斗。" },
      { en: "I have waited so long for this moment.", zh: "我等这一刻等了太久了。" },
      { en: "I have never been to Greece, but my cousin visited the country last year.", zh: "我从未去过希腊，但我表姐去年去了那个国家。" },
    ],
  },
  {
    id: 7,
    title: "The secret of memory",
    color: "#db667d",
    vocab: [
      { term: "regularly", pos: "adv.", meaning: "有规律地", family: ["regular adj. 有规律的"] },
      { term: "repeat", pos: "v.", meaning: "重复", family: ["repeated adj. 重复的"] },
      { term: "note", pos: "n.", meaning: "笔记；记录" },
      { term: "visual", pos: "adj.", meaning: "视觉的" },
      { term: "mentally", pos: "adv.", meaning: "精神上", family: ["mental adj. 精神的"] },
      { term: "link", pos: "v.", meaning: "联系；相联系" },
      { term: "list", pos: "n.", meaning: "清单" },
      { term: "especially", pos: "adv.", meaning: "尤其" },
      { term: "diet", pos: "n.", meaning: "日常饮食" },
      { term: "maintain", pos: "v.", meaning: "维持；保持" },
      { term: "nut", pos: "n.", meaning: "坚果" },
      { term: "relax", pos: "v.", meaning: "放松；休息", family: ["relaxed adj. 放松的", "relaxing adj. 令人放松的", "relaxation n. 放松"] },
      { term: "stressed", pos: "adj.", meaning: "心力交瘁的；焦虑不安的", family: ["stress n. 精神压力；紧张"] },
      { term: "tend", pos: "v.", meaning: "往往会；常常就" },
      { term: "normal", pos: "adj.", meaning: "正常的", family: ["normally adv. 正常地；通常"] },
      { term: "loss", pos: "n.", meaning: "丧失；损失" },
      { term: "fork", pos: "n.", meaning: "餐叉" },
      { term: "onion", pos: "n.", meaning: "洋葱" },
      { term: "ant", pos: "n.", meaning: "蚂蚁" },
      { term: "context", pos: "n.", meaning: "上下文；语境" },
      { term: "image", pos: "n.", meaning: "图像" },
      { term: "sense", pos: "n.", meaning: "感觉官能（即视、听、嗅、味、触五觉）" },
      { term: "summary", pos: "n.", meaning: "总结；概括", family: ["summarize v. 总结；概括"] },
      { term: "contain", pos: "v.", meaning: "包含；含有" },
      { term: "particular", pos: "adj.", meaning: "专指的；特指的" },
      { term: "chemistry", pos: "n.", meaning: "化学性质；化学", family: ["chemical adj. 化学的"] },
    ],
    phrases: [
      { term: "flash card", meaning: "识字卡片" },
      { term: "make a point of doing something", meaning: "（因重要或必要）保证做" },
      { term: "make up", meaning: "编造（故事、谎言等）" },
      { term: "as well as", meaning: "除……之外；也；还" },
      { term: "last but not least", meaning: "最后但同样重要的" },
      { term: "natural disaster", meaning: "自然灾害" },
      { term: "figure out", meaning: "弄懂；弄清楚" },
    ],
    sentences: [
      { en: "I find it difficult to remember things when I’m sleepy and tired, or not focused.", zh: "我发现，当我又困又累或无法集中注意力时，很难记住事情。" },
      { en: "For example, you can make up a story to link items in a list so that you will remember them.", zh: "例如，你可以编一个故事将列表中的项目联系起来，这样你就会记住它们。" },
      { en: "Unless you take time to relax, your brain will find it hard to remember things.", zh: "除非你花时间放松，否则你的大脑会难以记住事情。" },
      { en: "If you mix blue and yellow, you get green.", zh: "如果你把蓝色和黄色混合，你会得到绿色。" },
      { en: "This is a good sign as it means the tree grew well and was healthy.", zh: "这是个好迹象，因为这意味着树木生长良好且健康。" },
    ],
  },
  {
    id: 8,
    title: "Pets and us",
    color: "#8c64c5",
    vocab: [
      { term: "attack", pos: "v.", meaning: "袭击；攻击" },
      { term: "faithful", pos: "adj.", meaning: "忠实的；忠诚的" },
      { term: "hold", pos: "v.", meaning: "抱着；拿着" },
      { term: "responsible", pos: "adj.", meaning: "可信任的；可信赖的", family: ["responsibility n. 责任"] },
      { term: "awake", pos: "adj.", meaning: "醒着", family: ["awaken v.（使）醒来"] },
      { term: "flat", pos: "n.", meaning: "公寓" },
      { term: "choice", pos: "n.", meaning: "选择", family: ["choose v. 选择"] },
      { term: "advise", pos: "v.", meaning: "劝告；建议", family: ["advice n. 劝告；建议"] },
      { term: "cause", pos: "v.", meaning: "引起；造成；导致" },
      { term: "complain", pos: "v.", meaning: "抱怨；投诉", family: ["complaint n. 抱怨；投诉"] },
      { term: "litter", pos: "n.", meaning: "垃圾" },
      { term: "unlikely", pos: "adj.", meaning: "不太可能发生的" },
      { term: "relieve", pos: "v.", meaning: "方便；解手" },
      { term: "indoors", pos: "adv.", meaning: "在室内", family: ["indoor adj. 室内的"] },
      { term: "magical", pos: "adj.", meaning: "有魔力的", family: ["magic n. 魔力"] },
      { term: "wealth", pos: "n.", meaning: "钱财；财富", family: ["wealthy adj. 富有的"] },
      { term: "queen", pos: "n.", meaning: "女王；王后" },
      { term: "servant", pos: "n.", meaning: "仆人；佣人", family: ["serve v. 服务"] },
      { term: "pride", pos: "n.", meaning: "自豪；骄傲" },
      { term: "among", pos: "prep.", meaning: "在……中" },
      { term: "relationship", pos: "n.", meaning: "关系" },
    ],
    phrases: [
      { term: "grow up", meaning: "长大；成熟" },
      { term: "care for", meaning: "照顾；照料" },
      { term: "in short", meaning: "总之；简言之" },
      { term: "have no choice but to do", meaning: "别无选择；只能……" },
      { term: "run free", meaning: "四处自由走动" },
      { term: "lie around", meaning: "懒散度日；游手好闲" },
      { term: "complain about", meaning: "抱怨" },
      { term: "in addition", meaning: "除……以外（还）" },
      { term: "catch the eye of somebody", meaning: "引起某人的注意" },
    ],
    sentences: [
      { en: "It’s nice to hold them in our arms and play games with them.", zh: "把它们抱在怀里，和它们一起玩游戏，这种感觉很好。" },
      { en: "They have no choice but to keep their dogs inside most of the time.", zh: "他们别无选择，只能大部分时间把狗关在家里。" },
      { en: "Because of all these reasons, I would advise you not to get a dog as a pet.", zh: "由于上述这些原因，我建议你不要养狗作为宠物。" },
      { en: "You need to smile cheerfully when customers enter the shop.", zh: "当顾客进入商店时，你需要愉快地微笑。" },
      { en: "However, she washed Silver (the) most carefully because Silver is her favourite!", zh: "然而，她给 Silver 洗澡最仔细，因为 Silver 是她的最爱！" },
      { en: "If you keep a pet cat, it is unlikely that your neighbours will complain that it makes a loud noise.", zh: "如果你养了一只宠物猫，你的邻居不太可能会抱怨它发出很大的声响。" },
    ],
  },
];

export const allVocabulary = units.flatMap((unit) =>
  unit.vocab.map((item, index) => ({ ...item, unit: unit.id, index })),
);

