export const ipa: Record<string, string> = {
  "dinosaur": "ˈdaɪnəˌsɔr",
  "intelligent": "ˌɪnˈtɛləʤənt",
  "talented": "ˈtæləntɪd",
  "artistic": "ɑrˈtɪstɪk",
  "perhaps": "pərˈhæps",
  "notebook": "ˈnoʊtˌbʊk",
  "vehicle": "ˈviːɪkəl",
  "prehistoric": "ˌprihɪˈstɔrɪk",
  "completely": "kəmˈplitli",
  "original": "ərˈɪʤənəl",
  "birth": "bərθ",
  "suffering": "ˈsəfərɪŋ",
  "artist": "ˈɑrtɪst",
  "piece": "pis",
  "death": "dɛθ",
  "whole": "hoʊl",
  "editor": "ˈɛdɪtər",
  "organize": "ˈɔrgəˌnaɪz",
  "order": "ˈɔrdər",
  "record": "rɪˈkɔːd",
  "flight": "flaɪt",
  "schedule": "ˈʃedjuːl",
  "everywhere": "ˈɛvriˌwɛr",
  "challenge": "ˈʧælənʤ",
  "prize": "praɪz",
  "promise": "ˈprɑməs",
  "chessboard": "ˈʧɛsˌbɔrd",
  "silver": "ˈsɪlvər",
  "reply": "rɪˈplaɪ",
  "hesitation": "ˌhɛzəˈteɪʃən",
  "wonder": "ˈwəndər",
  "agree": "əˈgri",
  "per cent": "pər sɛnt",
  "currently": "ˈkərəntli",
  "check": "ʧɛk",
  "budget": "ˈbəʤɪt",
  "province": "ˈprɑvɪns",
  "sharply": "ˈʃɑrpli",
  "count": "kaʊnt",
  "system": "ˈsɪstəm",
  "symbol": "ˈsɪmbəl",
  "represent": "ˌrɛprɪˈzɛnt",
  "exactly": "ɪgˈzæktli",
  "network": "ˈnɛtˌwərk",
  "flood": "fləd",
  "multimedia": "ˌməltiˈmidiə",
  "expert": "ˈɛkspərt",
  "mobile": "ˈmoʊbəl",
  "payment": "ˈpeɪmənt",
  "warn": "wɔrn",
  "treatment": "ˈtritmənt",
  "data": "ˈdeɪtə",
  "company": "ˈkəmpəˌni",
  "traffic": "ˈtræfɪk",
  "flow": "floʊ",
  "smoothly": "ˈsmuːðli",
  "laptop": "ˈlæpˌtɑp",
  "screen": "skrin",
  "weight": "weɪt",
  "digital": "ˈdɪʤɪtəl",
  "social": "ˈsoʊʃəl",
  "message": "ˈmɛsɪʤ",
  "interview": "ˈɪntərvˌju",
  "positive": "ˈpɑzətɪv",
  "negative": "ˈnɛgətɪv",
  "effect": "ˈifɛkt",
  "opinion": "əˈpɪnjən",
  "novel": "ˈnɑvəl",
  "comment": "ˈkɑmɛnt",
  "basis": "ˈbeɪsɪs",
  "microprocessor": "ˌmaɪkroʊˈprɑsɛsər",
  "microchip": "ˈmaɪˌkroʊˈʧɪp",
  "major": "ˈmeɪʤər",
  "breakthrough": "ˈbreɪkθˌru",
  "electronic": "ˌɪˌlɛkˈtrɑnɪk",
  "software": "ˈsɔfˌwɛr",
  "app": "æp",
  "era": "ˈɪrə",
  "download": "ˈdaʊnˌloʊd",
  "tiny": "ˈtaɪni",
  "balloon": "bəˈlun",
  "wheel": "wil",
  "central": "ˈsɛntrəl",
  "although": "ˌɔlˈðoʊ",
  "attach": "əˈtæʧ",
  "pull": "pʊl",
  "international": "ˌɪntəˈnæʃənəl",
  "path": "pæθ",
  "technique": "tɛkˈnik",
  "depend": "dɪˈpɛnd",
  "doubt": "daʊt",
  "personally": "ˈpərsənəli",
  "prediction": "priˈdɪkʃən",
  "statement": "ˈsteɪtmənt",
  "benefit": "ˈbɛnəfɪt",
  "wing": "wɪŋ",
  "distance": "ˈdɪstəns",
  "petrol": "ˈpetrəl",
  "avoid": "əˈvɔɪd",
  "anywhere": "ˈɛniˌwɛr",
  "notice": "ˈnoʊtɪs",
  "type": "taɪp",
  "mixture": "ˈmɪksʧər",
  "heat": "hit",
  "press": "prɛs",
  "metal": "ˈmɛtəl",
  "exchange": "ɪksˈʧeɪnʤ",
  "nervous": "ˈnərvəs",
  "grateful": "ˈgreɪtfəl",
  "chopstick": "ˈʧɑpˌstɪk",
  "tour": "tʊə",
  "tai chi": "ˌtaɪ ˈtʃiː",
  "yet": "jɛt",
  "independent": "ˌɪndɪˈpɛndənt",
  "content": "ˈkɑntɛnt",
  "feeling": "ˈfilɪŋ",
  "shock": "ʃɑk",
  "foreign": "ˈfɔrən",
  "confused": "kənfˈjuzd",
  "anxious": "ˈæŋʃəs",
  "phase": "feɪz",
  "honeymoon": "ˈhəniˌmun",
  "unfamiliar": "ˌənfəˈmɪljər",
  "homesick": "ˈhoʊmˌsɪk",
  "lonely": "ˈloʊnli",
  "deal": "dil",
  "expect": "ɪkˈspɛkt",
  "situation": "ˌsɪʧuˈeɪʃən",
  "accept": "əkˈsɛpt",
  "adaptation": "ˌædəpˈteɪʃən",
  "author": "ˈɔθər",
  "remains": "rɪˈmeɪnz",
  "locate": "ˈloʊˌkeɪt",
  "soldier": "ˈsoʊlʤər",
  "captain": "ˈkæptən",
  "empty": "ˈɛmti",
  "victory": "ˈvɪktəri",
  "joke": "ʤoʊk",
  "midnight": "ˈmɪdˌnaɪt",
  "except": "ɪkˈsɛpt",
  "hide": "haɪd",
  "secretly": "ˈsikrɪtli",
  "enter": "ˈɛnər",
  "succeed": "səkˈsid",
  "trick": "trɪk",
  "fight": "faɪt",
  "beat": "bit",
  "pretend": "priˈtɛnd",
  "enemy": "ˈɛnəmi",
  "fail": "feɪl",
  "therefore": "ˈðɛrˌfɔr",
  "within": "wɪˈθɪn",
  "fill": "fɪl",
  "towards": "təˈwɔrdz",
  "attack": "əˈtæk",
  "fog": "fɔg",
  "regularly": "ˈrɛgjələrli",
  "repeat": "rɪˈpit",
  "note": "noʊt",
  "visual": "ˈvɪʒəwəl",
  "mentally": "ˈmɛnəli",
  "link": "lɪŋk",
  "list": "lɪst",
  "especially": "əˈspɛʃəli",
  "diet": "daɪət",
  "maintain": "meɪnˈteɪn",
  "nut": "nət",
  "relax": "rɪˈlæks",
  "stressed": "strɛst",
  "tend": "tɛnd",
  "normal": "ˈnɔrməl",
  "loss": "lɔs",
  "fork": "fɔrk",
  "onion": "ˈənjən",
  "ant": "ænt",
  "context": "ˈkɑntɛkst",
  "image": "ˈɪmɪʤ",
  "sense": "sɛns",
  "summary": "ˈsəməri",
  "contain": "kənˈteɪn",
  "particular": "ˌpɑˈtɪkjələr",
  "chemistry": "ˈkɛmɪstri",
  "faithful": "ˈfeɪθfəl",
  "hold": "hoʊld",
  "responsible": "riˈspɑnsəbəl",
  "awake": "əˈweɪk",
  "flat": "flæt",
  "choice": "ʧɔɪs",
  "advise": "ədˈvaɪz",
  "cause": "kɔz",
  "complain": "kəmˈpleɪn",
  "litter": "ˈlɪtər",
  "unlikely": "ənˈlaɪkli",
  "relieve": "rɪˈliv",
  "indoors": "ˈɪnˌdɔrz",
  "magical": "ˈmæʤɪkəl",
  "wealth": "wɛlθ",
  "queen": "kwin",
  "servant": "ˈsərvənt",
  "pride": "praɪd",
  "among": "əˈməŋ",
  "relationship": "riˈleɪʃənˌʃɪp",
  "Beijing opera": "ˌbeɪˈdʒɪŋ ˈɒpərə",
};

